### ISSUE TITLE
HeadlessException conflict with [SBM] Sheep Metal (depends on load order)

### ISSUE THREAD

**Issue by ProsperCraft** [comp500/ScreenshotToClipboard#2] opened 2019-07-12 03:16 UTC
I press F2, it says it saved a screenshot, but doesn't go in the clipboard.

**Comment by comp500** [comment] 2019-07-12 16:24
What version of Minecraft is this, and what operating system are you using?
What other mods are you using with this mod?

**Comment by ProsperCraft** [comment] 2019-07-12 16:32
Windows 10

https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

Forge .50

**Comment by comp500** [comment] 2019-07-13 18:18
Possible root cause discovered: A mod in the pack runs AWT libraries before Forge creates the mod classes

**Comment by comp500** [comment] 2019-07-14 02:05
The bug seems to go away when [SBM] Sheep Metal is removed from the pack, however I can't reproduce it with just Screenshot to Clipboard and [SBM] Sheep Metal, and I can't find any code in that mod to cause a conflict.

**Comment by comp500** [comment] 2019-07-14 02:11
Nevermind, I think I found the code that causes this - https://github.com/BuiltBrokenModding/SBM-SheepMetal/blob/master/src/main/java/com/builtbroken/sheepmetal/data/SheepTypes.java. I'll attempt a fix for this as soon as I can.

**Comment by comp500** [comment] 2019-07-14 16:54
I've submitted an issue to help resolve this, see https://github.com/BuiltBrokenModding/SBM-SheepMetal/issues/2

**Closed as completed** 2019-07-15 14:11 UTC
Labels: bug, 1.14, mod compat
